version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: insurance_rag_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
      POSTGRES_DB: insurance_rag
    ports:
      - "5433:5432" # Mapped to another port
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
